### ISSUE TITLE
Flag to not run nodehun

### ISSUE THREAD

**Issue by Garbee** [kdzwinel/Proofreader#12]
It would be nicer for extensions if we could get a flag to not run nodehun and only get the actual grammar suggestions. Different editors can have different ways to setup spell-checking with custom dictionaries by default which would provide better (and faster) integration then running it through this.

**Comment by crazy4groovy** [comment]
```
C:\>proofreader --url "http://www.google.ca"
module.js:491
    throw err;
    ^

Error: Cannot find module 'nodehun'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\solsen\AppData\Roaming\npm\node_modules\proofreader\lib\proofreader.js:6:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```
